services:
    app:
      container_name: app
      build: 
        dockerfile: ./docker/app/Dockerfile
        context: .
      ports:
        - "8080:8080"
      volumes:
        - type: bind
          source: ./src
          target: /src
